import{initializeApp}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';import{getAuth,GoogleAuthProvider,onAuthStateChanged,signInWithPopup,signOut}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
const FIREBASE_CONFIG={projectId:'yes-card-gacha-rgb',appId:'1:496431023991:web:b62a7768104553c9958372',storageBucket:'yes-card-gacha-rgb.firebasestorage.app',apiKey:'AIzaSyB8f7LK3UR-l2UgV_6qYPgAfDNfV4YlYrM',authDomain:'yes-card-gacha-rgb.firebaseapp.com',messagingSenderId:'496431023991'},ADMIN='info@rgb-workshop.com',ROOT='https://firestore.googleapis.com/v1/projects/yes-card-gacha-rgb/databases/(default)/documents/miniGames/yesCardGacha',$=s=>document.querySelector(s),auth=getAuth(initializeApp(FIREBASE_CONFIG)),provider=new GoogleAuthProvider();let config;
const labels={title:'遊戲名稱',eyebrow:'英文眉題',subtitle:'遊戲說明',balanceLabel:'現有分數標籤',costLabel:'抽卡費用標籤',drawButton:'抽卡按鈕（可用 {cost}）',drawingButton:'抽卡動畫文字',insufficient:'分數不足提示',resultEyebrow:'抽中卡片英文',resultTitle:'抽中卡片標題',againButton:'再扭一次按鈕',closeButton:'收起卡片按鈕',returnButton:'回到故事按鈕',albumButton:'卡簿按鈕（可用 {count}）',albumTitle:'卡簿標題',emptyAlbum:'空卡簿提示',scoreUnit:'分數單位'};
async function fallback(){return(await fetch('config.json',{cache:'no-store'})).json()}async function load(){const r=await fetch(ROOT,{cache:'no-store'});if(r.status===404)return fallback();if(!r.ok)throw new Error(`讀取失敗 (${r.status})`);const d=await r.json(),p=d.fields?.payload?.stringValue;return p?JSON.parse(p):fallback()}function msg(text,error=false){$('#message').textContent=text;$('#message').classList.toggle('error',error)}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){document.title='香港扭卡機｜管理後台';$('#coverUrl').value=config.settings.coverUrl;$('#startingCredits').value=config.settings.startingCredits;$('#drawCost').value=config.settings.drawCost;$('#textFields').innerHTML='';Object.entries(labels).forEach(([k,l])=>{$('#textFields').insertAdjacentHTML('beforeend',`<label>${l}<input data-text="${k}" value="${esc(config.texts[k])}"></label>`)});renderCards()}
function renderCards(){$('#cards').innerHTML='';config.cards.forEach((c,i)=>{const el=document.createElement('article');el.className='card';el.innerHTML=`<b>卡片 ${i+1}</b><div class="card-grid"><label>卡名<input data-key="name" value="${esc(c.name)}" required></label><label>2:3 圖片 URL<input data-key="image" value="${esc(c.image)}" required></label><label>稀有度<input data-key="rarity" value="${esc(c.rarity)}"></label><label>抽中權重<input data-key="weight" type="number" min="0.01" step="0.01" value="${Number(c.weight)||1}" required></label></div><button type="button" class="remove">刪除此卡</button>`;el.querySelector('.remove').onclick=()=>{if(config.cards.length<=1)return msg('最少需要一張卡。',true);read();config.cards.splice(i,1);renderCards()};$('#cards').appendChild(el)})}
function read(){config.settings={coverUrl:$('#coverUrl').value.trim(),startingCredits:Number($('#startingCredits').value)||0,drawCost:Number($('#drawCost').value)||0};document.querySelectorAll('[data-text]').forEach(x=>config.texts[x.dataset.text]=x.value.trim());config.cards=[...document.querySelectorAll('.card')].map((el,i)=>({id:`card-${i+1}`,name:el.querySelector('[data-key=name]').value.trim(),image:el.querySelector('[data-key=image]').value.trim(),rarity:el.querySelector('[data-key=rarity]').value.trim(),weight:Number(el.querySelector('[data-key=weight]').value)||1}))}
async function reload(){msg('正在載入…');try{config=await load();render();msg('已載入目前公開設定。')}catch(e){msg(e.message,true)}}async function publish(e){e.preventDefault();read();if(!config.cards.length)return msg('最少需要一張卡。',true);msg('正在發佈…');try{const token=await auth.currentUser.getIdToken(true),r=await fetch(ROOT,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({fields:{payload:{stringValue:JSON.stringify(config)},updatedAt:{timestampValue:new Date().toISOString()}}})});if(!r.ok)throw new Error(`發佈失敗 (${r.status}) ${await r.text()}`);msg('發佈成功！前台重新開啟後會使用新設定。')}catch(e){msg(e.message,true)}}
$('#loginButton').onclick=async()=>{try{await signInWithPopup(auth,provider)}catch(e){$('#loginMessage').textContent=`登入失敗：${e.message}`}};$('#logout').onclick=()=>signOut(auth);$('#reload').onclick=reload;$('#editor').onsubmit=publish;$('#addCard').onclick=()=>{read();config.cards.push({id:`card-${Date.now()}`,name:'新卡片',image:'assets/ferry-card.png',rarity:'普通卡',weight:1});renderCards()};onAuthStateChanged(auth,async u=>{const ok=u?.email?.toLowerCase()===ADMIN&&u.emailVerified;if(u&&!ok){await signOut(auth);$('#loginMessage').textContent=`此帳戶沒有管理權限：${u.email}`;return}$('#login').hidden=!!ok;$('#editor').hidden=!ok;$('#logout').hidden=!ok;if(ok){$('#userEmail').textContent=u.email;await reload()}});
